<a href="https://colab.research.google.com/github/Mat9408/Atividades_CursoAnalistaDeDados_EBAC/blob/main/M%C3%B3dulo_23_Tarefa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np

In [ ]:
penguins_df = sns.load_dataset('penguins')

In [ ]:
penguins_df.head(344)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [ ]:
penguins_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

###Valores nulos

In [ ]:
'''Remover todos os valores nulos do dataframe'''
penguins_df= penguins_df.dropna()
penguins_df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

###Variáveis numéricas

In [ ]:
'''Calculando a média e desvio padrão
da coluna bill_length_mm (comprimento do bico)'''

media_bill_length = penguins_df['bill_length_mm'].mean()
print(media_bill_length)

desvio_bill_length = penguins_df['bill_length_mm'].std()
print(desvio_bill_length)

43.99279279279279
5.468668342647559

In [ ]:
'''Criando a coluna bill_length_mm_std'''

penguins_df['bill_length_mm_std'] = penguins_df['bill_length_mm'].apply(lambda bill_length: (bill_length - media_bill_length) / desvio_bill_length)

In [ ]:
penguins_df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_std
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,-0.894695
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,-0.821552
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,-0.675264
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,-1.333559
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,-0.858123

In [ ]:
'''Calculando a média e o desvio padrão
da coluna bill_depth_mm (profundidade do bico)'''

media_bill_depth = penguins_df['bill_depth_mm'].mean()
print(media_bill_depth)

desvio_bill_depth = penguins_df['bill_depth_mm'].std()
print(desvio_bill_depth)

17.164864864864864
1.9692354633199007

In [ ]:
'''Criando a coluna bill_depth_mm_std'''

penguins_df['bill_depth_mm_std'] = penguins_df['bill_depth_mm'].apply(lambda bill_depth: (bill_depth - media_bill_depth) / desvio_bill_depth)

In [ ]:
penguins_df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_std,bill_depth_mm_std
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,-0.894695,0.779559
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,-0.821552,0.119404
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,-0.675264,0.424091
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,-1.333559,1.084246
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,-0.858123,1.744400

In [ ]:
'''Calculando a média e desvio padrão
da coluna flipper_length_mm (tamanho da nadadeira)'''

media_flipper_length = penguins_df['flipper_length_mm'].mean()
print(media_flipper_length)

desvio_flipper_length = penguins_df['flipper_length_mm'].std()
print(desvio_flipper_length)

200.96696696696696
14.015765288287879

In [ ]:
'''Criando a coluna flipper_length_mm_std'''

penguins_df['flipper_length_mm_std'] = penguins_df['flipper_length_mm'].apply(lambda flipper_length: (flipper_length - media_flipper_length) / desvio_flipper_length)

In [ ]:
penguins_df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_std,bill_depth_mm_std,flipper_length_mm_std
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,-0.894695,0.779559,-1.424608
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,-0.821552,0.119404,-1.067867
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,-0.675264,0.424091,-0.425733
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,-1.333559,1.084246,-0.568429
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,-0.858123,1.744400,-0.782474

In [ ]:
'''Calculando a média e desvio padrão
da coluna body_mass_g (massa corporal)'''

media_body_mass = penguins_df['body_mass_g'].mean()
print(media_body_mass)

desvio_body_mass = penguins_df['body_mass_g'].std()
print(desvio_body_mass)

4207.057057057057
805.2158019428965

In [ ]:
'''Criando a coluna body_mass_g_std'''

penguins_df['body_mass_g_std'] = penguins_df['body_mass_g'].apply(lambda body_mass: (body_mass - media_body_mass) / desvio_body_mass)

In [ ]:
penguins_df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_std,bill_depth_mm_std,flipper_length_mm_std,body_mass_g_std
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,-0.894695,0.779559,-1.424608,-0.567621
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,-0.821552,0.119404,-1.067867,-0.505525
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,-0.675264,0.424091,-0.425733,-1.188572
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,-1.333559,1.084246,-0.568429,-0.940192
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,-0.858123,1.744400,-0.782474,-0.691811

###Variáveis categóricas

In [ ]:
'''Transformando a coluna sex em valores numéricos inteiros
através da técnica one hot encoding'''

penguins_df['sex_m_nom'] = penguins_df['sex'].apply(lambda sex: 1 if sex == 'Male' else 0)
penguins_df['sex_f_nom'] = penguins_df['sex'].apply(lambda sex: 1 if sex == 'Female' else 0)

In [ ]:
penguins_df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_std,bill_depth_mm_std,flipper_length_mm_std,body_mass_g_std,sex_m_nom,sex_f_nom
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,-0.894695,0.779559,-1.424608,-0.567621,1,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,-0.821552,0.119404,-1.067867,-0.505525,0,1
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,-0.675264,0.424091,-0.425733,-1.188572,0,1
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,-1.333559,1.084246,-0.568429,-0.940192,0,1
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,-0.858123,1.744400,-0.782474,-0.691811,1,0

In [ ]:
penguins_df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_std,bill_depth_mm_std,flipper_length_mm_std,body_mass_g_std,sex_m_nom,sex_f_nom
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,-0.894695,0.779559,-1.424608,-0.567621,1,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,-0.821552,0.119404,-1.067867,-0.505525,0,1
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,-0.675264,0.424091,-0.425733,-1.188572,0,1
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,-1.333559,1.084246,-0.568429,-0.940192,0,1
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,-0.858123,1.744400,-0.782474,-0.691811,1,0

###Limpeza

In [ ]:
'''Limpando as colunas originais do DataFrame'''

penguins_df = penguins_df.drop(['island','bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g', 'sex'], axis= 1)

In [ ]:
penguins_df = penguins_df[['species', 'bill_length_mm_std', 'bill_depth_mm_std', 'flipper_length_mm_std', 'body_mass_g_std', 'sex_m_nom', 'sex_f_nom']]

In [ ]:
penguins_df.head(400)

,species,bill_length_mm_std,bill_depth_mm_std,flipper_length_mm_std,body_mass_g_std,sex_m_nom,sex_f_nom
0,Adelie,-0.894695,0.779559,-1.424608,-0.567621,1,0
1,Adelie,-0.821552,0.119404,-1.067867,-0.505525,0,1
2,Adelie,-0.675264,0.424091,-0.425733,-1.188572,0,1
4,Adelie,-1.333559,1.084246,-0.568429,-0.940192,0,1
5,Adelie,-0.858123,1.744400,-0.782474,-0.691811,1,0
...,...,...,...,...,...,...,...
338,Gentoo,0.586470,-1.759497,0.929884,0.891616,0,1
340,Gentoo,0.513326,-1.454811,1.001232,0.798473,0,1
341,Gentoo,1.171621,-0.743875,1.500670,1.916186,1,0
342,Gentoo,0.220750,-1.200905,0.787187,1.233139,0,1
343,Gentoo,1.080191,-0.540750,0.858536,1.481520,1,0